development: &default
  adapter: postgresql
  database: demoapp_development
  username: demoapp
  password: secret
  host: localhost 
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: demoapp_test